### ISSUE TITLE
Deployment in Vercel fails in CHF currency

### ISSUE THREAD

**Issue by balthasars** [thorwebdev/nextjs-subscription-payments#31]
# Bug report

## Describe the bug

I set up products in CHF currency in Stripe, unfortunately the build in Vercel then doesn't succeed. 
Upon changing them to USD, the build works. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Set products in Stripe as CHF
2. Deploy in Vercel as suggested

## Screenshots

```
17:24:45.574  	Cloning gitlab.com/balthasars/k_coffee (Branch: master, Commit: cdbb4fb)
17:24:46.360  	Cloning completed in 786ms
17:24:46.364  	Analyzing source code...
17:24:48.045  	Installing build runtime...
17:24:48.659  	Build runtime installed: 614.116ms
17:24:49.876  	Installing dependencies...
17:24:50.181  	yarn install v1.22.4
17:24:50.273  	[1/4] Resolving packages...
17:24:50.710  	[2/4] Fetching packages...
17:25:01.999  	info fsevents@2.1.3: The platform "linux" is incompatible with this module.
17:25:01.999  	info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
17:25:02.008  	info fsevents@1.2.13: The platform "linux" is incompatible with this module.
17:25:02.008  	info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
17:25:02.013  	[3/4] Linking dependencies...
17:25:02.025  	warning " > tailwindcss@2.0.1" has unmet peer dependency "autoprefixer@^10.0.2".
17:25:07.488  	[4/4] Building fresh packages...
17:25:09.354  	Done in 19.18s.
17:25:09.382  	Running "yarn run build"
17:25:09.729  	yarn run v1.22.4
17:25:09.765  	$ next build
17:25:10.749  	info  - Creating an optimized production build...
17:25:10.768  	Attention: Next.js now collects completely anonymous telemetry regarding usage.
17:25:10.769  	This information is used to shape Next.js' roadmap and prioritize features.
17:25:10.769  	You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
17:25:10.769  	https://nextjs.org/telemetry
17:25:34.031  	info  - Compiled successfully
17:25:34.031  	info  - Collecting page data...
17:25:34.671  	info  - Generating static pages (0/9)
17:25:35.114  	info  - Generating static pages (2/9)
17:25:35.146  	info  - Generating static pages (4/9)
17:25:35.180  	info  - Generating static pages (6/9)
17:25:35.476  	Unhandled error during request: TypeError: Cannot read property 'currency' of undefined
17:25:35.476  	    at /vercel/workpath0/.next/serverless/pages/index.js:2380:29
17:25:35.476  	    at Array.map (<anonymous>)
17:25:35.476  	    at Pricing (/vercel/workpath0/.next/serverless/pages/index.js:2374:28)
17:25:35.476  	    at d (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
17:25:35.476  	    at bb (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
17:25:35.476  	    at a.b.render (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
17:25:35.476  	    at a.b.read (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
17:25:35.476  	    at exports.renderToString (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
17:25:35.476  	    at Object.renderPage (/vercel/workpath0/node_modules/next/dist/next-server/server/render.js:53:851)
17:25:35.476  	    at Function.getInitialProps (/vercel/workpath0/.next/serverless/pages/index.js:2749:19)
17:25:35.476  	Error occurred prerendering page "/en-US". Read more: https://err.sh/next.js/prerender-error
17:25:35.476  	TypeError: Cannot read property 'currency' of undefined
17:25:35.476  	    at /vercel/workpath0/.next/serverless/pages/index.js:2380:29
17:25:35.477  	    at Array.map (<anonymous>)
17:25:35.477  	    at Pricing (/vercel/workpath0/.next/serverless/pages/index.js:2374:28)
17:25:35.477  	    at d (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
17:25:35.477  	    at bb (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
17:25:35.477  	    at a.b.render (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
17:25:35.477  	    at a.b.read (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
17:25:35.477  	    at exports.renderToString (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
17:25:35.477  	    at Object.renderPage (/vercel/workpath0/node_modules/next/dist/next-server/server/render.js:53:851)
17:25:35.477  	    at Function.getInitialProps (/vercel/workpath0/.next/serverless/pages/index.js:2749:19)
17:25:35.477  	> Build error occurred
17:25:35.477  	info  - Generating static pages (9/9)
17:25:35.483  	Error: Export encountered errors on following paths:
17:25:35.483  		/en-US
17:25:35.483  	    at exportApp (/vercel/workpath0/node_modules/next/dist/export/index.js:30:1103)
17:25:35.483  	    at runMicrotasks (<anonymous>)
17:25:35.483  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
17:25:35.483  	    at async build (/vercel/workpath0/node_modules/next/dist/build/index.js:39:69)
17:25:35.519  	error Command failed with exit code 1.
17:25:35.519  	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
17:25:35.531  	Error: Command "yarn run build" exited with 1
17:25:39.929  	Done with "package.json"
```

**Comment by thorwebdev** [comment]
@balthasars I'm not able to reproduce this.

In order for things to work properly, you first need to deploy the project to Vercel, which sets up the webhook endpoint for the syncing of products and prices, only one the deployment has finished you can start creating products in Stripe. These will then be synced to your Supabase DB:
![image](https://user-images.githubusercontent.com/5748289/102309734-6664ca80-3fa4-11eb-9d91-1f9868ac798b.png)

Could it be that you have some incomplete product or pricing details in your Supabase DB?

**Comment by balthasars** [comment]
Right — got it working now, I had already created products beforehand. 
Thank you for the solution and the great work!
